project:
  type: website
  output-dir: docs

website:
  title: "Learning Splunk - Use-Cases"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: splunk-search.qmd
        text: Splunk Search

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto